### ISSUE TITLE
May I use the code cocoa-activity-counter?

### ISSUE THREAD

**Issue by hoony6134** [daniel-beck/changelog-environment-plugin#3]
@daniel-beck May I use the code cocoa-activity-counter?
I want to modify some of code or some images and distribute to app store / site.
May I use your code?

p.s. I wrote here since that repository is archived.
Thanks!

**Comment by daniel-beck** [comment]
The repository readme states the license it is published under: CC-BY-SA. While not an ideal software license, it's the same license as content inline on Super User would have been under at the time, if I recall correctly.

It's basically a few lines of sample code with an Xcode project around it, just note the handful of methods I call and write your own from scratch 😉

**Comment by hoony6134** [comment]
Thank you!
